### ISSUE TITLE
[BUG] <Update link to raise an issue>

### ISSUE THREAD

**Issue by Mannuel25** [CommunityPro/support#113]
### Description of the bug

The current link to raise an issue is invalid: `Did we leave any important FAQ, raise an issue to add them here [Issue](https://github.com/CommunityPro/support/blob/main)`

### Project stack or language (e.g. front-end)

front-end

### Working Environment (e.g. operating system, browser, device)

Windows, Chrome, Laptop

**Comment by Evavic44** [comment]
Awesome job @Mannuel25 🙌🏾

**Comment by Mannuel25** [comment]
> Awesome job @Mannuel25 🙌🏾

Thanks man :wink:
