### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by thatsuman** [CommunityPro/support#132]
### Name

Suman Mondal

### Discord Username (if applicable) E.g John#412

suman#5129

### Questions & suggestions?

Hi Folks,
I'm looking for beginner friendly open source projects to work on. would be helpful if anyone help me to find one. 
Thanks!.

**Comment by Evavic44** [comment]
Welcome to the community @thatsuman we are so glad to have you with us. 

Yes, we actually encourage newbies to contribute to our projects. You can check out our latest project: <a href="https://github.com/CommunityPro/portfolio-html">portfolio-html</a>

Also, if you're looking to practice, add your profile to this <a href="https://github.com/CommunityPro/Practice-Contribution">project</a>
Welcome once again. 🙌🏾🙂
