### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by thuongtruong1009** [CommunityPro/support#141]
### Name

Tran Nguyen Thuong Truong

### Discord Username (if applicable) E.g John#412

thuongtruong1009

### Questions & suggestions?

I hope to learn and cooperate with friends!
Thank you!

**Comment by Evavic44** [comment]
Welcome to the community @thuongtruong1009 We're glad to have you join us. 🤩

**Comment by thuongtruong1009** [comment]
> Welcome to the community @thuongtruong1009 We're glad to have you join us. 🤩

Thank you very much!
Somethings very interesting in there
You're handsome 🥰
Have a nice day!
Thank you!
