### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by AvidCoder101** [CommunityPro/support#148]
### Name

Avid Coder

### Questions & suggestions?

I'd love to contribute (:

**Comment by Mannuel25** [comment]
Welcome to the community @AvidCoder101 !🥳


You can start your first contribution to the [Practice Contribution repository](https://github.com/CommunityPro/Practice-Contribution).

**Comment by Evavic44** [comment]
Welcome to the community @AvidCoder101 😎
