### ISSUE TITLE
Please invite me to the Community Organization

### ISSUE THREAD

**Issue by RedEdge967** [CommunityPro/support#154]
### Name

Chandula Janith

### Discord Username (if applicable) E.g John#412

Spider-Man#4119

**Comment by Evavic44** [comment]
Welcome to the community @RedEdge967 we are so pleased to have you here. 🤩

**Comment by RedEdge967** [comment]
it's Nice to meet you guys

**Comment by Evavic44** [comment]
Likewise. 😎
