### ISSUE TITLE
Add Issue Templates

### ISSUE THREAD

**Issue by Mannuel25** [CommunityPro/support#18]
I'd love to add more issue templates such as bug, idea templates to the repository

**Comment by Evavic44** [comment]
Sure man, go ahead. Simply rename this issue to `Add Issue Template` or anything similar to help understand what it is all about.

**Comment by Mannuel25** [comment]
> Sure man, go ahead. Simply rename this issue to `Add Issue Template` or anything similar to help understand what it is all about.

Okay, I'll. Thanks
