### ISSUE TITLE
Please invite me to the Community Organization

### ISSUE THREAD

**Issue by Jummate** [CommunityPro/support#37]
### Name

Jummate

**Comment by Evavic44** [comment]
Welcome to the community @Jummate

Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can read more on how to do that, <a href="https://github.com/CommunityPro/support#-how-to-make-the-organization-public">here</a>.

### Tips for practising:
Now you are a member, add your profile to this practice repo, you can find instructions on how to add your name to the README <a href="https://github.com/CommunityPro/Practice-Contribution#practice-contribution">here</a>
