### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by BlueEyeGod** [CommunityPro/support#4]
### Name

Cyril

### Additional Context

Heard it from a friend and wanted to share and learn from the community

**Comment by Evavic44** [comment]
Hey, @BlueEyeGod hope you're doing great? 
Can you please the issue again?  

The action has been fixed, so you should get an invitation to the community now. 
Just raise an issue here: <a href="https://github.com/CommunityPro/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+Community+Organization">Invitation</a>
