### ISSUE TITLE
Invitation request

### ISSUE THREAD

**Issue by mercyharbo** [CommunityPro/support#40]
I'd like to be part of the community as I possess skills in frontend engineering such as React js, JavaScript, Node js, CSS3, HTML5, Sass and many others.

**Comment by Evavic44** [comment]
> I'd like to be part of the community as I possess skills in frontend engineering such as React js, JavaScript, Node js, CSS3, HTML5, Sass and many others.

Hello Mercy, kindly use this link to register. <a href="https://github.com/CommunityPro/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+Community+Organization">Invite Me</a>
