### ISSUE TITLE
Please invite me to the Community Organization

### ISSUE THREAD

**Issue by 0tuedon** [CommunityPro/support#44]
### Name

Tuedon Tuoyo 

### Discord Username (if applicable) E.g John#412

0tuedon

### Questions & suggestions?

Can we get tasks

**Comment by Evavic44** [comment]
Thank you for requesting to join this community. 🤩 Check your email for an invitation link.

**Comment by Evavic44** [comment]
> ### Name
> 
> Tuedon Tuoyo
> ### Discord Username (if applicable) E.g John#412
> 
> 0tuedon
> ### Questions & suggestions?
> 
> Can we get tasks

Sure, we're starting our first project next week. So tasks will be assigned to everyone. 🥳
