### ISSUE TITLE
Sign me up

### ISSUE THREAD

**Issue by vermilion4** [CommunityPro/support#46]
Interested in joining the community.

**Comment by Evavic44** [comment]
Hello Vermilion, 🤩 kindly use this link to get invited to the community. 

<a href="https://github.com/CommunityPro/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+Community+Organization">Invitation Link</a>

**Comment by vermilion4** [comment]
Thank you @Evavic44

**Comment by Evavic44** [comment]
You're welcome!
