### ISSUE TITLE
[Favicon] <Favicon for our communitypro logo>

### ISSUE THREAD

**Issue by Melford-D** [CommunityPro/support#53]
## Favicon for our Logo
Favicon will help to improve our website view on browser tab.

### Add several screenshots or links related to the idea or feature (if applicable)

![apple-touch-icon](https://user-images.githubusercontent.com/67881299/148037933-56bdd9af-4d3b-403c-a6a6-0ba2f54bbbb4.png)

**Comment by Evavic44** [comment]
What service did you use for the favicons?
We will need to get the favicons to support different browsers and different screen sizes.

Here's an awesome service I use to generate the favicons
https://favicon.io/favicon-converter/

And the code will look like this
```html
<link rel="apple-touch-icon" sizes="180x180" href="./img/favicon/apple-touch-icon.png"/>
<link rel="icon" type="image/png" sizes="32x32" href="./img/favicon/favicon-32x32.png"/>
<link rel="icon" type="image/png" sizes="16x16" href="./img/favicon/favicon-16x16.png"/>
<link rel="icon" sizes="192x192" href="./img/favicon/android-chrome-192x192.png"/>
<link rel="icon" sizes="512x512" href="./img/favicon/android-chrome-512x512.png"/>
<link rel="manifest" href="img/favicon/site.webmanifest" />
```

**Comment by Melford-D** [comment]
I used https://iconifier.net/ and it provided similar results as the one you're recommending.

**Comment by Evavic44** [comment]
> .

Nice. 👍🏾🥳
