### ISSUE TITLE
[Join button] <Join button on the communitypro website>

### ISSUE THREAD

**Issue by Melford-D** [CommunityPro/support#54]
## Join Button
A join button will help to redirect new members to our github support/create issue page.

### Add several screenshots or links related to the idea or feature (if applicable)

![mobile view](https://user-images.githubusercontent.com/67881299/148038484-ae146b8d-1da2-451b-8236-d325c3a46811.png)

### Add more details about the idea or feature

nil

**Comment by Evavic44** [comment]
Thanks for making the updates to the form. 👍🏾

**Comment by Melford-D** [comment]
> Thanks for making the updates to the form. 👍🏾

My pleasure 🙂
