### ISSUE TITLE
Please invite me to the Community Organization

### ISSUE THREAD

**Issue by Destiny-01** [CommunityPro/support#60]
### Name

Destiny Aigbe

### Discord Username (if applicable) E.g John#412

diac#4913

**Comment by Evavic44** [comment]
Hello @Destiny-01 👋🏾 Welcome to Communitypro 🤩🙌🏾

**Comment by Evavic44** [comment]
Hello @Destiny-01 👋🏾 Welcome to Communitypro 🤩🙌🏾
