### ISSUE TITLE
Details

### ISSUE THREAD

**Issue by mimicodegirl** [CommunityPro/support#77]
Name: Banire Mariam
Skills: HTML, CSS, BOOTSTRAP

**Comment by Evavic44** [comment]
Hello @mimicodegirl thank you for showing an interest to join the community, 🙂 use this link to register. <a href="https://github.com/CommunityPro/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+Community+Organization"><b>LINK</b></a> 

Also, kindly remove your personal information in the above message for safety reasons.

**Comment by mimicodegirl** [comment]
Hello,

Thank you for your help. How do I remove the details? It is taking me back to a blank page. I would appreciate your help on this.
Best regards.

**Comment by Evavic44** [comment]
Click this menu button and you should see edit there, remove the details and save.

Here is a screenshot. 👇🏾
![delete](https://user-images.githubusercontent.com/62628408/148231638-f6f2115b-112f-44f2-9c01-2320c0d56156.png)

**Comment by mimicodegirl** [comment]
Thank you so much.

**Comment by Evavic44** [comment]
Sure thing @mimicodegirl 

Now register with this link 👇🏾
<a href="https://github.com/CommunityPro/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+Community+Organization">Registration</a>
