### ISSUE TITLE
[FEATURE REQUEST] <Add tag mention feature>

### ISSUE THREAD

**Issue by Evavic44** [CommunityPro/support#89]
### Description of the idea or feature

In the **community.yml** <a href="https://github.com/CommunityPro/support/blob/main/.github/workflows/community.yml">issue template</a>, add a tag mention attribute to allow the bot mention contributors to the project.

To tag a contributor in the message?
Use @contributor_name anywhere in the message and it will be automatically be replaced by the contributor's username.

## E.g
```yml
Thank you for raising an Issue in this community! @contributor_name
If you are willing to join the community, connect via 
```

### Add several screenshots or links related to the idea or feature (if applicable)

<img src="https://user-images.githubusercontent.com/62628408/148181464-0a9a5fac-657a-4011-8309-fc629615d66c.png" width="700px">

**Comment by frankiefab100** [comment]
How about adding the contributor's name immediately after `Thank you`.

e.g ``Thank you @contributor_name for raising an Issue in this community! 
If you are willing to join the community, connect via ...``

**Comment by Evavic44** [comment]
> How about adding the contributor's name immediately after `Thank you`.
> 
> e.g `Thank you @contributor_name for raising an Issue in this community! If you are willing to join the community, connect via ...`

That is a great idea. Do you want to fix this? I can assign you to do it.

**Comment by frankiefab100** [comment]
Yes, let me fix it.

**Comment by Mannuel25** [comment]
![IMG_20220106_162206](https://user-images.githubusercontent.com/68563757/148419130-2c1fd825-61f9-476c-9b6f-8181be386bee.jpg)

I got a notification today..but it still doesn't reference the person that raised the issue. The message shows `contributor_name`. Could you look into this @frankiefab100

**Comment by Evavic44** [comment]
I have a hunch it is caused by the `<strong></strong>` tag the text is wrapped in, I could be wrong. But it's something to consider.

**Comment by frankiefab100** [comment]
@Mannuel25 let me check it out

**Comment by frankiefab100** [comment]
I think a new GitHub account should be created which act as a bot and added as a contributor inorder to write on this repository.

[Credit](https://github.com/garg3133/welcome-new-contributors/blob/main/README.md)

**Comment by Evavic44** [comment]
> I think a new GitHub account should be created which act as a bot and added as a contributor inorder to write on this repository.
> 
> [Credit](https://github.com/garg3133/welcome-new-contributors/blob/main/README.md)

Love this idea. once the account is created, will let you know

**Comment by Evavic44** [comment]
Profile created. https://github.com/cpro-bot

**Comment by frankiefab100** [comment]
> Profile created. https://github.com/cpro-bot
Please ensure it appears as a contributor to give it write access.

**Comment by Evavic44** [comment]
> > Profile created. https://github.com/cpro-bot
> > Please ensure it appears as a contributor to give it write access.

Yeah, I already have.
